targets:
  $default:
    sources:
      include:
        - $package$
        - lib/$lib$
        - pubspec.*
        - lib/models/**
      exclude:
        - lib/components/**
    builders:
      json_serializable:
        options:
          any_map: true
          checked: false
          create_factory: true
          create_to_json: false
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true
