name: chaldea
description: Chaldea center.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  archive: ^2.0.13
  auto_size_text: ^2.1.0
  cached_network_image: ^2.5.0
  carousel_slider: 2.3.1
  catcher: ^0.3.23
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.1+1
  dio: ^3.0.10
  flutter_easyloading: ^2.2.2
  flutter_email_sender: ^4.0.0
  flutter_picker: ^1.1.5
  file_picker_cross: ^4.2.6
  flutter_qjs: ^0.2.2
  flutter_staggered_grid_view: ^0.4.0-nullsafety.2
  flutter_swiper: ^1.1.6
  html: ^0.14.0+4
  intl: ^0.17.0-nullsafety.2
  json_annotation: ^3.1.1
  json_patch: ^2.1.0
  logger: ^0.9.4
  package_info: ^0.4.3+2
  path_provider: ^1.6.24
  share: '>=0.6.5+4 <2.0.0'
  url_launcher: ^5.7.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.10.7
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_ios: "res/img/launcher_icon/ic_ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  image_path_android: "res/img/launcher_icon/ic_android_foreground.png"
#  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "res/img/launcher_icon/ic_android_foreground.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/img/launcher_icon/
    - res/data/
    - res/img/
    - res/js/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
#  main_locale: zh
