name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Describe the details and upload screenshots if necessary"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) the app is running on?
      multiple: true
      options:
        - web
        - iOS
        - Android
        - Windows
        - macOS
    validations:
      required: true
  - type: input
    id: device-info
    attributes:
      label: Device Info
      description: You can also fill more information about your device and OS.
      placeholder: iOS 15.2, Windows 10 21H2
  - type: dropdown
    id: region
    attributes:
      label: Which game server is related to this issue?
      multiple: true
      options:
        - JP
        - CN
        - TW
        - NA
        - KR
  - type: input
    id: version
    attributes:
      label: App Version
      description: The full version with build number(1.7.0+700) in About page. For web, also paste the commit hash please.
      placeholder: "1.7.0+700 9d3e35"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. Logs should be saved at `root_path/logs/*.log`.
      render: shell
