name: Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [windows, linux, android]
        include:
          # - os: macos-10.15 # Catalina
          #   target: macOS
          #   build_target: macos
          #   build_path: build/macos/Build/Products/Release
          #   asset_extension: .zip
          #   asset_content_type: application/zip
          - os: windows-latest
            target: windows
            build_target: windows
            build_path: build\windows\runner\Release
            asset_extension: .zip
            asset_content_type: application/zip
          - os: ubuntu-latest
            target: linux
            build_target: linux
            build_path: build/linux/x64/release/bundle
            asset_extension: .tar.gz
            asset_content_type: application/gzip
          - os: ubuntu-latest
            target: android
            build_target: apk
            build_path: build/app/outputs/flutter-apk
            asset_extension: .apk
            asset_content_type: application/vnd.android.package-archive
      fail-fast: false
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.13.0-0.1.pre"
          channel: "beta"
          cache: true

      - name: Install Linux dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev

      - name: Install Android dependencies
        if: matrix.target == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Enable desktop support
        if: matrix.target != 'android'
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - name: Checkout chaldea code
        uses: actions/checkout@v2

      - name: Remove invalid pub packages
        if: matrix.target == 'linux'
        run: sed -i 's/just_audio_libwinmedia/# just_audio_libwinmedia/g' pubspec.yaml

      - name: Configure Keystore for Android
        if: matrix.target == 'android'
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android
      - name: Configure Android Preview package name
        if: matrix.target == 'android' && github.ref == 'refs/heads/main'
        run: dart ./scripts/patch_android_preview.dart

      - name: Generate git info
        run:  dart ./scripts/generate_git_info.dart

      - run: flutter pub get
      - run: flutter build ${{ matrix.build_target }} -v --release

      # Package the build.
      - name: Copy VC redistributables to release directory for Windows
        if: matrix.target == 'windows'
        run: |
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
        working-directory: ${{ matrix.build_path }}
      - name: Rename build for Android
        if: matrix.target == 'android'
        run: mv app-release.apk $GITHUB_WORKSPACE/chaldea-preview-${{ matrix.target }}.apk
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for Linux
        if: matrix.target == 'linux'
        run: tar czf $GITHUB_WORKSPACE/chaldea-preview-${{ matrix.target }}.tar.gz *
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for macOS
        if: matrix.target == 'macOS'
        run: ditto -c -k --sequesterRsrc --keepParent Chaldea.app $GITHUB_WORKSPACE/chaldea-preview-${{ matrix.target }}.zip
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for Windows
        if: matrix.target == 'windows'
        run: compress-archive -Path * -DestinationPath ${env:GITHUB_WORKSPACE}\chaldea-preview-${{ matrix.target }}.zip
        working-directory: ${{ matrix.build_path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chaldea-preview-${{ matrix.target }}
          path: ./chaldea-preview-${{ matrix.target }}${{ matrix.asset_extension }}


  publish-canary:
    name: Publish Canary
    if: github.ref == 'refs/heads/main'
    needs: create-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u +"%Y/%m/%d %H:%M:%S %Z")"
      - uses: actions/download-artifact@v3
      - run: ls -l -R

      - name: Delete previous canary build
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Publish release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: canary
          name: Chaldea Preview
          body: Built at ${{ steps.get-date.outputs.date }}
          draft: false
          prerelease: true
          artifacts: "chaldea-preview-*/*"
