name: Deploy web

on:
   push:
     branches:
       - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
          channel: 'beta'
          cache: true
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get

      - name: Build with web-renderer=canvaskit
        run: |
            flutter build web --web-renderer canvaskit
            dart ./scripts/patch_web_build.dart

      - name: Push to app repo
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: chaldea-center/app
          target_branch: main
          build_dir: build/web
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Build with web-renderer=html
        run: |
            rm -rf build/web/
            flutter build web --web-renderer html
            dart ./scripts/patch_web_build.dart
      
      - name: Publish to app repo html branch
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: chaldea-center/app
          target_branch: html
          build_dir: build/web
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}
